#!/bin/bash

# $1: EPUB file path
EPUB=${1}
EPUB_SAFETY=`echo ${EPUB} | sed "s/[^A-Za-z0-9]/_/g"`

SCRIPTPATH=./scripts
DATAPATH=../data
TEMPROOT=./makegrasphy_temp
TEMPPATH=${TEMPROOT}/${EPUB_SAFETY}
CURPATH=`pwd`

# make temporary directory
if [ ! -e ${TEMPROOT} ]; then
	mkdir ${TEMPROOT}
fi

# extract EPUB
unzip ${EPUB} -d ${TEMPPATH} >/dev/null

# analyze
for filename in `find ${TEMPPATH} -name *.html`; do
	echo ${filename}

	python3 ${SCRIPTPATH}/extract_sentence.py ${filename} > ${filename}.sent 2>/dev/null
	${SCRIPTPATH}/sentence-boundary <${filename}.sent >${filename}.sent.split 2>/dev/null
	python3 ${SCRIPTPATH}/add_sentence_tag.py ${filename} > ${filename}.with_no 2>/dev/null
	${SCRIPTPATH}/stanford-tokenizer < ${filename}.sent.split > ${filename}.tok 2>/dev/null
	${SCRIPTPATH}/stanford-parser-long < ${filename}.sent.split > ${filename}.parse 2>/dev/null
	python3 ${SCRIPTPATH}/convert_sentence.py ${filename} ${filename}.with_no ${filename}.parse 2>/dev/null
	
	rm ${filename}.sent
	rm ${filename}.sent.split
	rm ${filename}.with_no
	rm ${filename}.parse
done

# calculate difficulty
python3 ${SCRIPTPATH}/calc_difficulty.py ${TEMPPATH} ${DATAPATH}/wordcount.txt
find ${TEMPPATH} -name *.tok | xargs rm

# make EPUB for Grasphy
cd ${TEMPPATH}
zip -r ${CURPATH}/${EPUB_SAFETY}.grasphy * >/dev/null
cd ${CURPATH}

# dispose temporary data
rm -rf ${TEMPPATH}

