#!/bin/bash

source settings.sh

java \
	-cp ${MYCLASSPATH}/stanford-postagger.jar \
	-Xmx512m \
	edu.stanford.nlp.tagger.maxent.MaxentTagger \
	-model ${MYCLASSPATH}/stanford-postagger-models/english-bidirectional-distsim.tagger \
	-sentenceDelimiter newline

